version: '2'

services:
  understand-quran:
    build: ./understand-quran/docker
    command: /build.sh
    ports:
      - 3000:3000
    volumes:
      - ./understand-quran/docker/build.sh:/build.sh
      - ./understand-quran/code:/code
    depends_on:
      - verdaccio
  storybook:
    build: ./understand-quran/docker
    command: /build-storybook.sh
    ports:
      - 6006:6006
    volumes:
      - ./understand-quran/docker/build-storybook.sh:/build-storybook.sh
      - ./understand-quran/code:/code
    depends_on:
      - verdaccio
  verdaccio:
    build: ./npm-registry/docker
    ports:
      - 4873:4873
    volumes:
      - ./npm-registry/code/storage:/verdaccio/storage
      - ./npm-registry/code/conf:/verdaccio/conf
      - ./npm-registry/code/plugins:/verdaccio/plugins
