#!/bin/bash

set -x
set -e

npm_registry=http://npm-registry:4873

# Wait till 'npm-registry' container is up
while ! curl $npm_registry 1> /dev/null
do
  echo "$(date) - waiting for npm-registry ..."
  sleep 1
done

# Set working directory
cd /code

# Install packages
yarn install

# Lint
while ! yarn run lint
do
  echo "$(date) - restarting server ..."
  sleep 1
done

/re-publish

# Build and run storybook
while ! (yarn run build-stories && yarn run start-storybook)
do
  echo "$(date) - restarting server ..."
  sleep 1
done
