ls: 
  .tsx: PascalCase
  .d.ts: PascalCase
  .scss: camelCase
  .module.scss: camelCase
  .js: regex:^$
  .jsx: regex:^$
  .ts: regex:^$
  .html: regex:^$
  .css: regex:^$

ignore:
  - ./node_modules
  - ./next-env.d.ts
  - ./.eslintrc.js
  - ./.next
  - ./next.config.js
  - ./pages/_app.tsx
  - ./pages/index.tsx
  - ./copies
  - ./lib/index.ts
  - ./utils
