ls: 
  .tsx: PascalCase
  .stories.tsx: PascalCase
  .scss: camelCase
  .js: regex:^$
  .jsx: regex:^$
  .html: regex:^$
  .css: regex:^$

ignore:
  - ./node_modules
  - ./.eslintrc.js
  - ./src/utils
  - ./storybook-static
  - ./.storybook
  - ./stories
  - ./webpack.prod.js
  - ./dist
